name: "EKS"
on:
  workflow_dispatch:

jobs:
  Plan:
    uses: sahil-randhawa/k8tf-challenge/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: sahil-randhawa/k8tf-challenge/.github/workflows/aws_tf_apply.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
